import React from "react";
import styled from "@emotion/styled";

import Layout from "../layout";
import IntroductionSection from "./intro";
import Testimonials from "./testimonials";
import WhatWeDoSection from "./what-we-do";
import HowItFunctions from "./how-it-functions";
import Teams from "./teams";

const HeaderSection = styled('section')`
  min-height: 35vmin;
  display: flex;
  align-items: center;
  padding: 5vh 1rem;
`;

const AboutPage = () => (
    <Layout title="About Woodman 123 Team">
        <HeaderSection>
            <h1 className="font-bold text-4xl md:text-4xl lg:text-5xl xl:text-6xl">
                About Woodman 123 Team
            </h1>
        </HeaderSection>
        <div className="p-3">
            <IntroductionSection/>
            <HowItFunctions/>
            <WhatWeDoSection/>
            {/*<Teams />*/}
            <Testimonials/>
            <p className="mb-5">
                <cite>
                    NOTE: Some of this is generated by LLM.
                </cite>
            </p>
        </div>
    </Layout>
);

export default AboutPage;
